-- Add team collaboration support to workspaces
-- Adds workspace type (personal vs team) and invite code for joining teams

-- Workspace type: personal (default, single-user) or team (multi-user collaboration)
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS type VARCHAR(20) NOT NULL DEFAULT 'personal'
    CHECK (type IN ('personal', 'team'));

-- Invite code for team workspaces (8-char alphanumeric, unique)
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS invite_code VARCHAR(20) UNIQUE;

-- Auto-generate invite codes for existing team workspaces (none expected yet)
-- New team workspaces will get codes generated by the application layer

CREATE INDEX IF NOT EXISTS idx_workspaces_type ON workspaces(type);
CREATE INDEX IF NOT EXISTS idx_workspaces_invite_code ON workspaces(invite_code) WHERE invite_code IS NOT NULL;
